<?php
echo '';
echo '<!doctype html>';
echo '<html lang="en">';
echo '<head>';
echo '<title>ColorVision Cosmetics</title>';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<link rel="stylesheet" href="css/bootstrap.min.css">';
echo '<link rel="shortcut icon" href="icons/favicon.png">';
echo '<link href="icons/themify-icons/themify-icons.css" rel="stylesheet">';
echo '<link href="css/style.css" rel="stylesheet">';
echo '<link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">';
echo '</head>';
echo '<body onload="myFunction()">';
echo '<!--spinner loader-->';
echo '<div id="sk-circle" class="sk-circle">';
echo '<div class="sk-circle1 sk-child"></div>';
echo '<div class="sk-circle2 sk-child"></div>';
echo '<div class="sk-circle3 sk-child"></div>';
echo '<div class="sk-circle4 sk-child"></div>';
echo '<div class="sk-circle5 sk-child"></div>';
echo '<div class="sk-circle6 sk-child"></div>';
echo '<div class="sk-circle7 sk-child"></div>';
echo '<div class="sk-circle8 sk-child"></div>';
echo '<div class="sk-circle9 sk-child"></div>';
echo '<div class="sk-circle10 sk-child"></div>';
echo '<div class="sk-circle11 sk-child"></div>';
echo '<div class="sk-circle12 sk-child"></div>';
echo '</div>';
echo '<!--end spinner loader-->';
echo '<div id="catalog" class="container-fluid animate-bottom">';
echo '<div class="row">';
echo '<!--utility bar-->';
echo '<nav class="navbar navbar-fixed-left navbar-minimal animate">';
echo '<div class="navbar-toggler animate">';
echo '<span class="menu-icon ti-plus icon-color"></span>';
echo '</div>';
echo '<ul class="navbar-menu animate">';
echo '<li>';
echo '<a id="Home" class="animate" href="index.php">';
echo '<span class="ti-home icon-color"></span>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<a id="zoomIn" class="animate">';
echo '<span class="ti-plus icon-color"></span>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<a id="zoomOut" class="animate">';
echo '<span class="ti-minus icon-color"></span>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<a data-toggle="tooltip" data-placement="right" title="open eyes" class="animate activefront">';
echo '<span class="ti-angle-up icon-color"></span>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<a data-toggle="tooltip" data-placement="right" title="close eyes" class="animate activeside">';
echo '<span class="ti-angle-down icon-color"></span>';
echo '</a>';
echo '</li>';
echo '</ul>';
echo '</nav>';
echo '<!--end utility bar-->';
echo '<!--left column-->';
echo '<!--empty view box-->';
echo '<div class="box-view"></div>';
echo '<!--front-view-->';
echo '<div id="desk-sx" class="front-view col-sm-12 col-md-8 tail">';
echo '<img src="img/background-open.jpg" alt="" class="img-responsive"/>';
echo '<img id="lip" src="img/lip-coral-open.png" alt="" class="img-responsive"/>';
echo '<img id="eye" src="img/eyeshadow-aqua-open.png" alt="" class="img-responsive"/>';
echo '<img id="highlighter" src="img/highlighter-cipria-open.png" alt="" class="img-responsive"/>';
echo '</div>';
echo '<!--side-view-->';
echo '<div id="desk-sx-side" class="side-view col-sm-12 col-md-8 tail">';
echo '<img src="img/background-close.jpg" alt="" class="img-responsive"/>';
echo '<img id="lip-side" src="img/lip-coral-close.png" alt="" class="img-responsive"/>';
echo '<img id="eye-side" src="img/eyeshadow-aqua-close.png" alt="" class="img-responsive"/>';
echo '<img id="highlighter-side" src="img/highlighter-cipria-close.png" alt="" class="img-responsive"/>';
echo '</div>';
echo '<!--end left column-->';
echo '<!--right column-->';
echo '<div id="desk-dx" class="col-sm-12 col-md-4">';
echo '<div id="desk-dx-top" class="col-sm-12 catalog">';
echo '<div id="mySidenav-13" class="sidenav-13">';
echo '<div class="top-logo col-xs-12">';
echo '<img class="logo image-responsive" alt="" src="img/logo.png"/>';
echo '</div>';
echo '<div onclick="closeNav13()" class="top-nav push-active col-xs-6">';
echo '<span class="ti-angle-left"></span><span class="tab-space">Back</span>';
echo '</div>';
echo '<div class="top-nav-name col-xs-12" data-toggle="collapse">';
echo '<span>New Arrivals</span>';
echo '</div>';
echo '<div data-toggle="tooltip" title="Too Faced" class="col-xs-6 product-tail frame">';
echo '<img class="image-responsive" alt="" src="img/product-1.jpg"/>';
echo '</div>';
echo '<div data-toggle="tooltip" title="Urban Decay" class="col-xs-6 product-tail frame">';
echo '<img class="image-responsive" alt="" src="img/product-2.jpg"/>';
echo '</div>';
echo '<div data-toggle="tooltip" title="Natasha Denona" class="col-xs-6 product-tail frame">';
echo '<img class="image-responsive" alt="" src="img/product-3.jpg"/>';
echo '</div>';
echo '<div data-toggle="tooltip" title="Huda Beauty" class="col-xs-6 product-tail frame">';
echo '<img class="image-responsive" alt="" src="img/product-4.jpg"/>';
echo '</div>';
echo '<div data-toggle="tooltip" title="Hourglass" class="col-xs-6 product-tail frame">';
echo '<img class="image-responsive" alt="" src="img/product-5.jpg"/>';
echo '</div>';
echo '<div data-toggle="tooltip" title="Nars" class="col-xs-6 product-tail frame">';
echo '<img class="image-responsive" alt="" src="img/product-6.jpg"/>';
echo '</div>';
echo '<div data-toggle="tooltip" title="Jacob Beauty" class="col-xs-6 product-tail frame">';
echo '<img class="image-responsive" alt="" src="img/product-7.jpg"/>';
echo '</div>';
echo '<div data-toggle="tooltip" title="Cake Pencil" class="col-xs-6 product-tail frame">';
echo '<img class="image-responsive" alt="" src="img/product-8.jpg"/>';
echo '</div>';
echo '</div>';
echo '<div id="mySidenav" class="sidenav">';
echo '<div class="top-logo col-xs-12">';
echo '<img class="logo image-responsive" alt="" src="img/logo.png"/>';
echo '</div>';
echo '<div class="top-banner col-xs-12">';
echo '<img class="banner image-responsive" alt="" src="img/banner.jpg"/>';
echo '</div>';
echo '<div id="product" onclick="openNav13()" class="top-nav-name col-xs-12" data-toggle="collapse">';
echo '<span>Products</span>';
echo '</div>';
echo '<div onclick="openNav7()" class="top-nav push-active col-xs-12">';
echo '<span>Checkout</span>';
echo '</div>';
echo '<ul class="list-group row">';
echo '<li onclick="openNav()" class="list-group-item col-xs-12">';
echo '<span class="chat-img pull-left">';
echo '<img width="50" class="img-responsive" alt="" src="icons/icon-1.svg">';
echo '</span>';
echo '<span>Eyeshadow</span>';
echo '<span class="tab-space"></span><span class="ti-angle-right"></span>';
echo '</li>';
echo '<li onclick="openNav3()" class="list-group-item col-xs-12">';
echo '<span class="chat-img pull-left">';
echo '<img width="50" class="img-responsive" alt="" src="icons/icon-2.svg">';
echo '</span>';
echo '<span>Lipstick</span>';
echo '<span class="tab-space"></span><span class="ti-angle-right"></span>';
echo '</li>';
echo '<li onclick="openNav4()" class="list-group-item col-xs-12">';
echo '<span class="chat-img pull-left">';
echo '<img width="50" class="img-responsive" alt="" src="icons/icon-3.svg">';
echo '</span>';
echo '<span>Highlighter</span>';
echo '<span class="tab-space"></span><span class="ti-angle-right"></span>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '<div id="mySidenav-2" class="sidenav-2">';
echo '<div onclick="closeNav()" class="top-nav push col-xs-6">';
echo '<span class="ti-angle-left"></span><span class="tab-space"></span>';
echo '<span>eyeshadow</span>';
echo '</div>';
echo '<div onclick="openNav7()" class="top-nav push-active col-xs-6">';
echo '<span>Checkout</span>';
echo '</div>';
echo '<ul class="list-group row">';
echo '<li onclick="document.getElementById('eye').src='img/eyeshadow-aqua-open.png', document.getElementById('eye-side').src='img/eyeshadow-aqua-close.png'" class="text list-group-item col-xs-12 activex select-1"  id='price1-1' data-price="25" data-code="aqua 2164671">';
echo '<span class="chat-img pull-left"><img class="img-rounded img-responsive" width="50" alt="" src="img/img-eye-aqua.jpg"></span>';
echo 'aqua<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('eye').src='img/eyeshadow-azure-open.png', document.getElementById('eye-side').src='img/eyeshadow-azure-close.png'" class="text list-group-item col-xs-12 select-1" id='price1-2' data-price="30" data-code="azure 2164676">';
echo '<span class="chat-img pull-left"><img class="img-rounded img-responsive" width="50" alt="" src="img/img-eye-azure.jpg"></span>';
echo 'azure<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('eye').src='img/eyeshadow-berry-open.png', document.getElementById('eye-side').src='img/eyeshadow-berry-close.png'" class="text list-group-item col-xs-12 select-1" id='price1-3' data-price="20" data-code="berry 2164675">';
echo '<span class="chat-img pull-left"><img class="img-rounded img-responsive" width="50" alt="" src="img/img-eye-berry.jpg"></span>';
echo 'berry<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('eye').src='img/eyeshadow-cipria-open.png', document.getElementById('eye-side').src='img/eyeshadow-cipria-close.png'" class="text list-group-item col-xs-12 select-1" id='price1-4' data-price="40" data-code="cipria 2474678">';
echo '<span class="chat-img pull-left"><img class="img-rounded img-responsive" width="50" alt="" src="img/img-eye-cipria.jpg"></span>';
echo 'cipria<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('eye').src='img/eyeshadow-fucsia-open.png', document.getElementById('eye-side').src='img/eyeshadow-fucsia-close.png'" class="text list-group-item col-xs-12 select-1" id='price1-5' data-price="25" data-code="fucsia 2154661">';
echo '<span class="chat-img pull-left"><img class="img-rounded img-responsive" width="50" alt="" src="img/img-eye-fucsia.jpg"></span>';
echo 'fucsia<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('eye').src='img/eyeshadow-golden-open.png', document.getElementById('eye-side').src='img/eyeshadow-golden-close.png'" class="text list-group-item col-xs-12 select-1" id='price1-6' data-price="40" data-code="golden 2364647">';
echo '<span class="chat-img pull-left"><img class="img-rounded img-responsive" width="50" alt="" src="img/img-eye-golden.jpg"></span>';
echo 'golden<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('eye').src='img/eyeshadow-green-open.png', document.getElementById('eye-side').src='img/eyeshadow-green-close.png'" class="text list-group-item col-xs-12 select-1" id='price1-7' data-price="30" data-code="green 5556786">';
echo '<span class="chat-img pull-left"><img class="img-rounded img-responsive" width="50" alt="" src="img/img-eye-green.jpg"></span>';
echo 'green<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('eye').src='img/eyeshadow-red-open.png', document.getElementById('eye-side').src='img/eyeshadow-red-close.png'" class="text list-group-item col-xs-12 select-1" id='price1-8' data-price="20" data-code="red 4568235">';
echo '<span class="chat-img pull-left"><img class="img-rounded img-responsive" width="50" alt="" src="img/img-eye-red.jpg"></span>';
echo 'red<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('eye').src='img/eyeshadow-smoke-open.png', document.getElementById('eye-side').src='img/eyeshadow-smoke-close.png'" class="text list-group-item col-xs-12 select-1" id='price1-9' data-price="25" data-code="smoke 3459723">';
echo '<span class="chat-img pull-left"><img class="img-rounded img-responsive" width="50" alt="" src="img/img-eye-smoke.jpg"></span>';
echo 'smoke<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('eye').src='img/eyeshadow-violet.png', document.getElementById('eye-side').src='img/eyeshadow-violet-close.png'" class="text list-group-item col-xs-12 select-1" id='price1-10' data-price="20" data-code="violet 4562189">';
echo '<span class="chat-img pull-left"><img class="img-rounded img-responsive" width="50" alt="" src="img/img-eye-violet.jpg"></span>';
echo 'violet<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '<div id="mySidenav-3" class="sidenav-3">';
echo '<div onclick="closeNav3()" class="top-nav push col-xs-6">';
echo '<span class="ti-angle-left"></span><span class="tab-space"></span>';
echo '<span>lipstick</span>';
echo '</div>';
echo '<div onclick="openNav7()" class="top-nav push-active col-xs-6">';
echo '<span>buy your makeup</span>';
echo '</div>';
echo '<ul class="list-group row">';
echo '<li onclick="document.getElementById('lip').src='img/lip-coral-open.png', document.getElementById('lip-side').src='img/lip-coral-close.png'" class="text list-group-item col-xs-12 activex select-2" id='price2-1' data-price="20" data-code="strawberry 4568233">';
echo '<span class="chat-img pull-left">';
echo '<img class="img-rounded img-responsive" width="50" alt="" src="img/img-lip-coral.jpg">';
echo '</span>';
echo 'strawberry kissed<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('lip').src='img/lip-berry-open.png', document.getElementById('lip-side').src='img/lip-berry-close.png'" class="text list-group-item col-xs-12 select-2" id='price2-2' data-price="30" data-code="endless-purple 1248452">';
echo '<span class="chat-img pull-left">';
echo '<img class="img-rounded img-responsive" width="50" alt="" src="img/img-lip-berry.jpg">';
echo '</span>';
echo 'endless purple<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('lip').src='img/lip-azure-open.png', document.getElementById('lip-side').src='img/lip-azure-close.png'" class="text list-group-item col-xs-12 select-2" id='price2-3' data-price="40" data-code="violet-vertigo 84939830">';
echo '<span class="chat-img pull-left">';
echo '<img class="img-rounded img-responsive" width="50" alt="" src="img/img-lip-azure.jpg">';
echo '</span>';
echo 'violet vertigo<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('lip').src='img/lip-cipria-open.png', document.getElementById('lip-side').src='img/lip-cipria-close.png'" class="text list-group-item col-xs-12 select-2" id='price2-4' data-price="50" data-code="cinder-rose 3455623">';
echo '<span class="chat-img pull-left">';
echo '<img class="img-rounded img-responsive" width="50" alt="" src="img/img-lip-cipria.jpg">';
echo '</span>';
echo 'cinder rose <span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('lip').src='img/lip-glam-open.png', document.getElementById('lip-side').src='img/lip-glam-close.png'" class="text list-group-item col-xs-12 select-2" id='price2-5' data-price="50" data-code="cherry-moon 9834567">';
echo '<span class="chat-img pull-left">';
echo '<img class="img-rounded img-responsive" width="50" alt="" src="img/img-lip-glam.jpg">';
echo '</span>';
echo 'cherry moon<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('lip').src='img/lip-green-open.png', document.getElementById('lip-side').src='img/lip-green-close.png'" class="text list-group-item col-xs-12 select-2" id='price2-5' data-price="50" data-code="stone-blue 4958903">';
echo '<span class="chat-img pull-left">';
echo '<img class="img-rounded img-responsive" width="50" alt="" src="img/img-lip-green.jpg">';
echo '</span>';
echo 'stone blue<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('lip').src='img/lip-lemon-open.png', document.getElementById('lip-side').src='img/lip-lemon-close.png'" class="text list-group-item col-xs-12 select-2" id='price2-5' data-price="50" data-code="pink-peony 4943450">';
echo '<span class="chat-img pull-left">';
echo '<img class="img-rounded img-responsive" width="50" alt="" src="img/img-lip-lemon.jpg">';
echo '</span>';
echo 'pink peony<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('lip').src='img/lip-pink-open.png', document.getElementById('lip-side').src='img/lip-pink-close.png'" class="text list-group-item col-xs-12 select-2" id='price2-5' data-price="50" data-code="sweet raspberry 3576203">';
echo '<span class="chat-img pull-left">';
echo '<img class="img-rounded img-responsive" width="50" alt="" src="img/img-lip-pink.jpg">';
echo '</span>';
echo 'sweet raspberry<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('lip').src='img/lip-red-open.png', document.getElementById('lip-side').src='img/lip-red-close.png'" class="text list-group-item col-xs-12 select-2" id='price2-5' data-price="50" data-code="chili-pepper 0934712">';
echo '<span class="chat-img pull-left">';
echo '<img class="img-rounded img-responsive" width="50" alt="" src="img/img-lip-red.jpg">';
echo '</span>';
echo 'chili pepper<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('lip').src='img/lip-smoke-open.png', document.getElementById('lip-side').src='img/lip-smoke-close.png'" class="text list-group-item col-xs-12 select-2" id='price2-5' data-price="50" data-code="black.cherry 8674362">';
echo '<span class="chat-img pull-left">';
echo '<img class="img-rounded img-responsive" width="50" alt="" src="img/img-lip-smoke.jpg">';
echo '</span>';
echo 'black Cherry<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('lip').src='img/lip-violet-open.png', document.getElementById('lip-side').src='img/lip-violet-close.png'" class="text list-group-item col-xs-12 select-2" id='price2-5' data-price="50" data-code="tender-love 0192845">';
echo '<span class="chat-img pull-left">';
echo '<img class="img-rounded img-responsive" width="50" alt="" src="img/img-lip-violet.jpg">';
echo '</span>';
echo 'tender love<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '<div id="mySidenav-4" class="sidenav-4">';
echo '<div onclick="closeNav4()" class="top-nav push col-xs-6">';
echo '<span class="ti-angle-left"></span><span class="tab-space"></span>';
echo '<span>highlighter</span>';
echo '</div>';
echo '<div onclick="openNav7()" class="top-nav push-active col-xs-6">';
echo '<span>buy your makeup</span>';
echo '</div>';
echo '<ul class="list-group row">';
echo '<li onclick="document.getElementById('highlighter').src='img/highlighter-cipria-open.png', document.getElementById('highlighter-side').src='img/highlighter-cipria-close.png'" class="text list-group-item col-xs-12 activex select-3" id='price3-1' data-price="25" data-code="amenthyst 356522">';
echo '<span class="chat-img pull-left"><img class="img-rounded img-responsive" width="50" alt="" src="img/img-highlighter-cipria.jpg"></span>';
echo 'amenthyst<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('highlighter').src='img/highlighter-brown-open.png', document.getElementById('highlighter-side').src='img/highlighter-brown-close.png'" class="text list-group-item col-xs-12 select-3" id='price3-2' data-price="30" data-code="cocoa 4563257">';
echo '<span class="chat-img pull-left"><img class="img-rounded img-responsive" width="50" alt="" src="img/img-highlighter-brown.jpg"></span>';
echo 'cocoa<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('highlighter').src='img/highlighter-fucsia-open.png', document.getElementById('highlighter-side').src='img/highlighter-fucsia-close.png'" class="text list-group-item col-xs-12 select-3" id='price3-3' data-price="30" data-code="orchid 9745673">';
echo '<span class="chat-img pull-left"><img class="img-rounded img-responsive" width="50" alt="" src="img/img-highlighter-fucsia.jpg"></span>';
echo 'orchid<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('highlighter').src='img/highlighter-glow-open.png', document.getElementById('highlighter-side').src='img/highlighter-glow-close.png'" class="text list-group-item col-xs-12 select-3" id='price3-4' data-price="35" data-code="glow 4532678">';
echo '<span class="chat-img pull-left"><img class="img-rounded img-responsive" width="50" alt="" src="img/img-highlighter-glow.jpg"></span>';
echo 'glow<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '<li onclick="document.getElementById('highlighter').src='img/highlighter-light-pink-open.png', document.getElementById('highlighter-side').src='img/highlighter-light-pink-close.png'" class="text list-group-item col-xs-12 select-3" id='price3-5' data-price="25" data-code="plum 1234563">';
echo '<span class="chat-img pull-left"><img class="img-rounded img-responsive" width="50" alt="" src="img/img-highlighter-pink.jpg"></span>';
echo 'plum<span class="tab-space"></span><span class="ti-pencil"></span>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '<div id="mySidenav-7" class="sidenav-7">';
echo '<div onclick="closeNav7()" class="top-nav push-active col-xs-6">';
echo '<span class="ti-angle-left"></span><span class="tab-space"></span>';
echo '<span>Back</span>';
echo '</div>';
echo '<div class="top-nav col-xs-6">';
echo '<span>Summary</span>';
echo '</div>';
echo '<ul class="list-group row">';
echo '<li onclick="closeNav10()" class=" list-group-summary col-xs-8">';
echo '<span class="chat-img pull-left">';
echo '<span class="ti-pencil"></span><span class="tab-space"></span>';
echo '</span>';
echo 'Color eyeshadow:<br>';
echo '<span class="list-group-code" id="code_3"></span>';
echo '</li>';
echo '<li onclick="closeNav10()" class=" list-group-item col-xs-4">';
echo '<p id='total'>0.00 $</p>';
echo '</li>';
echo '<li onclick="closeNav11()" class="list-group-summary col-xs-8">';
echo '<span class="chat-img pull-left">';
echo '<span class="ti-pencil"></span><span class="tab-space"></span>';
echo '</span>';
echo 'Color lipstick:<br>';
echo '<span class="list-group-code" id="code_2"></span>';
echo '</li>';
echo '<li onclick="closeNav11()" class="list-group-item col-xs-4">';
echo '<p id='total_2'>0.00 $</p>';
echo '</li>';
echo '<li onclick="closeNav14()" class="list-group-summary col-xs-8">';
echo '<span class="chat-img pull-left">';
echo '<span class="ti-pencil"></span><span class="tab-space"></span>';
echo '</span>';
echo 'Color highlighter:<br>';
echo '<span class="list-group-code" id="code_1"></span>';
echo '</li>';
echo '<li onclick="closeNav14()" class="list-group-item col-xs-4">';
echo '<p id='total_3'>0.00 $</p>';
echo '</li>';
echo '<li style="line-height:35px;" class="total list-group-summary col-xs-8">';
echo '<span class="chat-img pull-left">';
echo '<span class="ti-pencil-alt"></span><span class="tab-space"></span>';
echo '</span>';
echo 'Total price:<br>';
echo '</li>';
echo '<li onclick="" class="total list-group-item col-xs-4">';
echo '<span class="pull-right" style="padding-left: 5px;">$</span><p id="count_tot" >0.00</p>';
echo '</li>';
echo '</ul>';
echo '<button class="top-nav-qty col-xs-2 push-counter quantity-left-minus btn btn-number" type="button" data-type="minus">';
echo '<span class="ti-minus"></span>';
echo '</button>';
echo '<div class="top-nav-qty col-xs-2">';
echo '<input type="text" id="quantity" name="quantity" class="form-control input-number" value="1">';
echo '</div>';
echo '<button class="top-nav-qty col-xs-2 push-counter quantity-right-plus btn btn-number" type="button" data-type="plus">';
echo '<span class="ti-plus"></span>';
echo '</button>';
echo '<div class="top-nav-qty col-xs-6 push-box" id='num_item_basket'>';
echo '<span class="ti-package"></span><span class="tab-space"></span>';
echo '<span>add to box</span>';
echo '</div>';
echo '';
echo '';
echo '<div class="top-nav col-xs-6 push-active">';
echo '<span class="ti-location-arrow"></span><span class="tab-space"></span>';
echo '<span>select and pay</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!--end right column-->';
echo '</div>';
echo '</div>';
echo '<script src="js/jquery.min.js"></script>';
echo '<script src="js/bootstrap.min.js"></script>';
echo '<script src="js/summary.js"></script>';
echo '<script src="js/views.js"></script>';
echo '<script src="js/navigation.js"></script>';
echo '<script src="js/utility.js"></script>';
echo '</body>';
echo '</html>';
echo '';
?>